
set(OPENSUSE 0)

include(Platform/Linux/Distro/FindDetectFiles)

if(CAT AND SED)
    if(DEFINED OPENSUSE)
        if(EXISTS /etc/os-release)
            if(${OS_RELEASE_DISTRO} MATCHES "openSUSE")
                set(OPENSUSE 1)
            else()
                set(OPENSUSE 0)
            endif()
        elseif(EXISTS /etc/SUSE-release)
            exec_program(${CAT} ARGS /etc/SUSE-release OUTPUT_VARIABLE DISTRO_RELEASE_TEXT)
            exec_program(${SED} ARGS ${DISTRO_RELEASE_REGEX} ${DISTRO_RELEASE_TEXT} OUTPUT_VARIABLE DISTRO_RELEASE_DISTRO)
            string(FIND ${DISTRO_RELEASE_DISTRO} "openSUSE" OPENSUSE_POSITION)
            if(${OPENSUSE_POSITION} GREATER -1)
                set(OPENSUSE 1)
            else()
                set(OPENSUSE 0)
            endif()
        else()
            if(${LSB_RELEASE_DISTRO} MATCHES "SUSE LINUX")
                set(OPENSUSE 1)
            else()
                set(OPENSUSE 0)
            endif()
        endif()
    endif() 
endif()


unset(OS_RELEASE_DISTRO_REGEX)
unset(DISTRO_RELEASE_REGEX)
unset(LSB_RELEASE_REGEX)
unset(TRIM_VARIABLE_REGEX)
unset(REMOVE_NOT_MATCHED_OS)
unset(REMOVE_NOT_MATCHED_DISTRO)
unset(REMOVE_NOT_MATCHED_LSB)
