
set(SLACKWARE 0)

include(Platform/Linux/Distro/FindDetectFiles)

if(CAT AND SED)
    if(DEFINED SLACKWARE)
        if(EXISTS /etc/os-release)
            if(${OS_RELEASE_DISTRO} MATCHES "Slackware")
                set(SLACKWARE 1)
            else()
                set(SLACKWARE 0)
            endif()
        elseif(EXISTS /etc/slackware-version)
            exec_program(${CAT} ARGS /etc/slackware-version OUTPUT_VARIABLE DISTRO_RELEASE_TEXT)
            exec_program(${SED} ARGS ${DISTRO_RELEASE_REGEX} ${DISTRO_RELEASE_TEXT} OUTPUT_VARIABLE DISTRO_RELEASE_DISTRO)
            string(FIND ${DISTRO_RELEASE_DISTRO} "Slackware" SLACKWARE_POSITION)
            if(${SLACKWARE_POSITION} GREATER -1)
                set(SLACKWARE 1)
            else()
                set(SLACKWARE 0)
            endif()
        else()
            if(${LSB_RELEASE_DISTRO} MATCHES "Slackware")
                set(SLACKWARE 1)
            else()
                set(SLACKWARE 0)
            endif()
        endif()
    endif() 
endif()


unset(OS_RELEASE_DISTRO_REGEX)
unset(DISTRO_RELEASE_REGEX)
unset(LSB_RELEASE_REGEX)
unset(TRIM_VARIABLE_REGEX)
unset(REMOVE_NOT_MATCHED_OS)
unset(REMOVE_NOT_MATCHED_DISTRO)
unset(REMOVE_NOT_MATCHED_LSB)
