
set(CENTOS 0)

include(Platform/Linux/Distro/FindDetectFiles)

if(CAT AND SED)
    if(DEFINED CENTOS)
        if(EXISTS /etc/os-release)
            if(${OS_RELEASE_DISTRO} MATCHES "CentOS Linux")
                set(CENTOS 1)
            else()
                set(CENTOS 0)
            endif()
        elseif(EXISTS /etc/centos-release)
            exec_program(${CAT} ARGS /etc/centos-release OUTPUT_VARIABLE DISTRO_RELEASE_TEXT)
            exec_program(${SED} ARGS ${DISTRO_RELEASE_REGEX} ${DISTRO_RELEASE_TEXT} OUTPUT_VARIABLE DISTRO_RELEASE_DISTRO)
            string(FIND ${DISTRO_RELEASE_DISTRO} "CentOS" CENTOS_POSITION)
            if(${CENTOS_POSITION} GREATER -1)
                set(CENTOS 1)
            else()
                set(CENTOS 0)
            endif()
        else()
            string(FIND ${LSB_RELEASE_DISTRO} "CentOS" CENTOS_POSITION_LSB)
            if(${CENTOS_POSITION_LSB} GREATER -1)
                set(CENTOS 1)
            else()
                set(CENTOS 0)
            endif()
        endif()
    endif() 
endif()


unset(OS_RELEASE_DISTRO_REGEX)
unset(DISTRO_RELEASE_REGEX)
unset(LSB_RELEASE_REGEX)
unset(TRIM_VARIABLE_REGEX)
unset(REMOVE_NOT_MATCHED_OS)
unset(REMOVE_NOT_MATCHED_DISTRO)
unset(REMOVE_NOT_MATCHED_LSB)
 
