
set(ARCH_LINUX 0)

include(Platform/Linux/Distro/FindDetectFiles)

if(CAT AND SED)
    if(DEFINED ARCH_LINUX)
        if(EXISTS /etc/os-release)
            if(${OS_RELEASE_DISTRO} MATCHES "Arch Linux")
                set(ARCH_LINUX 1)
            else()
                set(ARCH_LINUX 0)
            endif()
        elseif(EXISTS /etc/arch-release)
            exec_program(${CAT} ARGS /etc/arch-release OUTPUT_VARIABLE DISTRO_RELEASE_TEXT)
            exec_program(${SED} ARGS ${DISTRO_RELEASE_REGEX} ${DISTRO_RELEASE_TEXT} OUTPUT_VARIABLE DISTRO_RELEASE_DISTRO) 
            if(${DISTRO_RELEASE_DISTRO} MATCHES "Arch Linux")
                set(ARCH_LINUX 1)
            else()
                set(ARCH_LINUX 0)
            endif()
        else()
            if(${LSB_RELEASE_DISTRO} MATCHES "archlinux")
                set(ARCH_LINUX 1)
            else()
                set(ARCH_LINUX 0)
            endif()
        endif()
    endif() 
endif()


unset(OS_RELEASE_DISTRO_REGEX)
unset(DISTRO_RELEASE_REGEX)
unset(LSB_RELEASE_REGEX)
unset(TRIM_VARIABLE_REGEX)
unset(REMOVE_NOT_MATCHED_OS)
unset(REMOVE_NOT_MATCHED_DISTRO)
unset(REMOVE_NOT_MATCHED_LSB)
