
set(WINDOWS_8 0)

include(Platform/Windows/Version/FindDetectFiles)


if(DEFINED WINDOWS_8)
    if(WMIC)
        string(FIND "${WMIC_CAPTION_LINE}" "Microsoft Windows 8" WINDOWS_8_POSITION)
        if(${WINDOWS_8_POSITION} GREATER -1)
            set(WINDOWS_8 1)
        else()
            set(WINDOWS_8 0)
        endif()
    elseif(SYSTEMINFO AND FINDSTR)
        string(FIND "${SYSTEM_INFO_LINE}" "Microsoft Windows 8" WINDOWS_8_POSITION)
        if(${WINDOWS_8_POSITION} GREATER -1)
            set(WINDOWS_8 1)
        else()
            set(WINDOWS_8 0)
        endif()
    else()
        execute_process(COMMAND cmd.exe /C ver OUTPUT_VARIABLE WIN_VER OUTPUT_STRIP_TRAILING_WHITESPACE)
        string(FIND "${WIN_VER}" "Version 6.2.9200.16384" WINDOWS_8_POSITION)
            if(${WINDOWS_8_POSITION} GREATER -1)
                set(WINDOWS_8 1)
            else()
                set(WINDOWS_8 0)
            endif()
    endif()
endif()   
