
set(WINDOWS_VISTA 0)

include(Platform/Windows/Version/FindDetectFiles)


if(DEFINED WINDOWS_VISTA)
    if(SYSTEMINFO AND FINDSTR)
        string(FIND ${SYSTEM_INFO_LINE} "Microsoftr Windows VistaT" WINDOWS_VISTA_POSITION)
        if(${WINDOWS_VISTA_POSITION} GREATER -1)
            set(WINDOWS_VISTA 1)
        else()
            set(WINDOWS_VISTA 0)
        endif()
    elseif(WMIC)
        string(FIND ${WMIC_CAPTION_LINE} "Microsoftr Windows VistaT" WINDOWS_VISTA_POSITION)
        if(${WINDOWS_VISTA_POSITION} GREATER -1)
            set(WINDOWS_VISTA 1)
        else()
            set(WINDOWS_VISTA 0)
        endif()
    else()
        if(VER)
            string(FIND ${WIN_VER} "Version 6.0.5048" WINDOWS_LONGHORN_POSITION)
            string(FIND ${WIN_VER} "Version 6.0" WINDOWS_VISTA_POSITION)
            if(${WINDOWS_VISTA_POSITION} GREATER -1 AND ${WINDOWS_LONGHORN_POSITION} GREATER -1)
                set(WINDOWS_VISTA 0)
            else()
                if(${WINDOWS_VISTA_POSITION} GREATER -1)
                    set(WINDOWS_VISTA 1)
                else()
                    set(WINDOWS_VISTA 0)
                endif()
            endif()
        endif()
    endif()
endif() 
