
set(WINDOWS_VISTA 0)

include(Platform/Windows/Version/FindDetectFiles)


if(DEFINED WINDOWS_XP)
    if(WMIC)
        string(FIND "${WMIC_CAPTION_LINE}" "Microsoft Windows XP" WINDOWS_XP_POSITION)
        if(${WINDOWS_XP_POSITION} GREATER -1)
            set(WINDOWS_XP 1)
        else()
            set(WINDOWS_XP 0)
        endif()
    elseif(SYSTEMINFO AND FINDSTR)
        string(FIND "${SYSTEM_INFO_LINE}" "Microsoft Windows XP" WINDOWS_XP_POSITION)
        if(${WINDOWS_XP_POSITION} GREATER -1)
            set(WINDOWS_XP 1)
        else()
            set(WINDOWS_XP 0)
        endif()
     else()
        execute_process(COMMAND cmd.exe /C ver OUTPUT_VARIABLE WIN_VER OUTPUT_STRIP_TRAILING_WHITESPACE)
        string(FIND "${WIN_VER}" "Microsoft Windows XP" WINDOWS_XP_POSITION)
        if(${WINDOWS_XP_POSITION} GREATER -1)
            set(WINDOWS_XP 1)
        else()
            set(WINDOWS_XP 0)
        endif()
     endif()
endif()
